
# Site settings
title: Zhiqing Hong
name: Zhiqing Hong
subtitle: Master student in computer science
email: hongzq@zju.edu.cn
description: >
  Master student in computer science
baseurl: ""
url: "https://killuakukuroo.github.io/"
github_username:  pesoto
disqus_baseurl: "https://killuakukuroo.github.io/"
disqus_shortname: https-killuakukuroo-github-io
permalink: :title
google-site-verification: "EBNpnv4GiHJTmePgRajamxrYtJnc6WlqDyWUITDaSMo"

# Build settings
markdown: kramdown
paginate: 5
paginate_path: "/page:num/"
inter_post_navigation: true

defaults:
  -
    scope:
      path: ""
    values:
      author: "Zhiqing Hong"



# External gems
gems:
  - jekyll-paginate
  - jemoji
  - jekyll-seo-tag



social:
  - name: GitHub
    icon: github
    username: killuakukuroo
    url: https://github.com/killuakukuroo
    desc: Fork me on GitHub
    share: false

  - name: LinkedIn
    icon: linkedin
    username: Paul E. Soto
    url: https://linkedin.com/pesoto
    desc: Connect with me on LinkedIn
    share: true
